import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';

const sourcePath = new URL('../data/generated/patro.json', import.meta.url);
const generatedPath = new URL('../internal/generated-data.ts', import.meta.url);
const metadataPath = new URL('../internal/data.ts', import.meta.url);
const source = JSON.parse(await readFile(sourcePath, 'utf8'));

function fail(message) {
  throw new Error(`Invalid Patro source: ${message}`);
}

if (!Array.isArray(source.table) || source.table.length === 0) fail('table must be non-empty');
if (!Array.isArray(source.prefix) || source.prefix.length !== source.table.length + 1) {
  fail('prefix must contain one offset per year plus the terminal offset');
}

const startYear = source.bsStart.year;
const patterns = [];
const patternIds = [];
const patternIndexes = new Map();

for (const [index, row] of source.table.entries()) {
  if (row.bsYear !== startYear + index) fail(`unexpected year at table index ${index}`);
  if (!Array.isArray(row.months) || row.months.length !== 12)
    fail(`year ${row.bsYear} must have 12 months`);
  if (row.months.some((days) => !Number.isInteger(days) || days < 29 || days > 32)) {
    fail(`year ${row.bsYear} contains an invalid month length`);
  }

  const key = JSON.stringify(row.months);
  let patternIndex = patternIndexes.get(key);
  if (patternIndex === undefined) {
    patternIndex = patterns.length;
    patterns.push(row.months);
    patternIndexes.set(key, patternIndex);
  }
  patternIds.push(patternIndex);

  const expectedPrefix = source.prefix[index] + row.months.reduce((sum, days) => sum + days, 0);
  if (expectedPrefix !== source.prefix[index + 1]) fail(`prefix mismatch for year ${row.bsYear}`);
}

if (source.prefix[0] !== 0) fail('prefix must start at zero');

function bsOrdinal(date) {
  const yearIndex = date.year - startYear;
  if (!Number.isInteger(date.year) || yearIndex < 0 || yearIndex >= source.table.length) {
    fail(`reference or endpoint year ${date.year} is outside the source table`);
  }
  if (!Number.isInteger(date.month) || date.month < 1 || date.month > 12) {
    fail(`reference or endpoint month ${date.month} is invalid`);
  }
  const months = source.table[yearIndex].months;
  const monthOffset = months.slice(0, date.month - 1).reduce((sum, days) => sum + days, 0);
  if (!Number.isInteger(date.day) || date.day < 1 || date.day > months[date.month - 1]) {
    fail(`reference or endpoint day ${date.day} is invalid`);
  }
  return source.prefix[yearIndex] + monthOffset + date.day - 1;
}

const totalDays = source.prefix[source.prefix.length - 1];
const checksum = createHash('sha256')
  .update(JSON.stringify(source.table))
  .digest('hex')
  .slice(0, 16);
if (source.checksum !== checksum)
  fail(`checksum mismatch: expected ${source.checksum}, calculated ${checksum}`);
const referenceOrdinal = bsOrdinal(source.referencePair.bs);
const startOrdinal = bsOrdinal(source.bsStart);
const endOrdinal = bsOrdinal(source.bsEnd);
if (startOrdinal !== 0) fail('bsStart must be the first source date');
if (endOrdinal !== totalDays - 1) fail('bsEnd must be the last source date');

function rawADToDayCount(year, month, day) {
  const a = Math.floor((14 - month) / 12);
  const adjustedYear = year + 4800 - a;
  const adjustedMonth = month + 12 * a - 3;
  const julianDay =
    day +
    Math.floor((153 * adjustedMonth + 2) / 5) +
    365 * adjustedYear +
    Math.floor(adjustedYear / 4) -
    Math.floor(adjustedYear / 100) +
    Math.floor(adjustedYear / 400) -
    32045;
  return julianDay - 2440588;
}

function rawDayCountToAD(dayCount) {
  const julianDay = dayCount + 2440588;
  const a = julianDay + 32044;
  const b = Math.floor((4 * a + 3) / 146097);
  const c = a - Math.floor((146097 * b) / 4);
  const d = Math.floor((4 * c + 3) / 1461);
  const e = c - Math.floor((1461 * d) / 4);
  const monthIndex = Math.floor((5 * e + 2) / 153);
  return {
    year: b * 100 + d - 4800 + Math.floor(monthIndex / 10),
    month: monthIndex + 3 - 12 * Math.floor(monthIndex / 10),
    day: e - Math.floor((153 * monthIndex + 2) / 5) + 1,
  };
}

const reference = source.referencePair.ad;
const epoch = rawADToDayCount(reference.year, reference.month, reference.day);
const adStart = rawDayCountToAD(epoch - referenceOrdinal + startOrdinal);
const adEnd = rawDayCountToAD(epoch - referenceOrdinal + endOrdinal);
const numberList = (values) => values.join(', ');
const dateLiteral = (date) =>
  `Object.freeze({ year: ${date.year}, month: ${date.month}, day: ${date.day} })`;

const generatedSource = `/* This file is generated by scripts/generate-data.mjs. */
export const MONTH_PATTERNS: readonly (readonly number[])[] = [
${patterns.map((pattern) => `  [${numberList(pattern)}],`).join('\n')}
] as const;

export const YEAR_PATTERN_IDS: readonly number[] = [${numberList(patternIds)}] as const;

export const YEAR_PREFIX: readonly number[] = [${numberList(source.prefix)}] as const;
`;

const metadataSource = `/* This file is generated by scripts/generate-data.mjs. */
export interface MetadataDate {
  readonly year: number;
  readonly month: number;
  readonly day: number;
}

export interface ReferencePair {
  readonly bs: MetadataDate;
  readonly ad: MetadataDate;
  readonly note: string;
}

export interface DateMetadata {
  readonly bsStart: MetadataDate;
  readonly bsEnd: MetadataDate;
  readonly adStart: MetadataDate;
  readonly adEnd: MetadataDate;
  readonly totalDays: number;
  readonly checksum: string;
  readonly sourceRevision: string;
  readonly referencePair: ReferencePair;
}

const bsStart = ${dateLiteral(source.bsStart)};
const bsEnd = ${dateLiteral(source.bsEnd)};
const adStart = ${dateLiteral(adStart)};
const adEnd = ${dateLiteral(adEnd)};
const referencePair = Object.freeze({
  bs: ${dateLiteral(source.referencePair.bs)},
  ad: ${dateLiteral(source.referencePair.ad)},
  note: ${JSON.stringify(source.referencePair.note)},
});

export const metadata: DateMetadata = Object.freeze({
  bsStart,
  bsEnd,
  adStart,
  adEnd,
  totalDays: ${totalDays},
   checksum: ${JSON.stringify(checksum)},
  sourceRevision: ${JSON.stringify(source.sourceRevision)},
  referencePair,
});
`;

await mkdir(new URL('../internal/', import.meta.url), { recursive: true });
await writeFile(generatedPath, generatedSource);
await writeFile(metadataPath, metadataSource);
