// Generated by `pnpm generate:admin` from src/admin/data/raw/*.json.
// DO NOT EDIT. Revision: gov-2026-09. See PROVENANCE.md.
import type { District } from '../types.js';

export const DISTRICTS: readonly District[] = [
  {
    "code": "101",
    "province": "1",
    "nameEn": "Taplejung",
    "nameNe": "ताप्लेजुङ"
  },
  {
    "code": "102",
    "province": "1",
    "nameEn": "Sankhuwasabha",
    "nameNe": "संखुवासभा"
  },
  {
    "code": "103",
    "province": "1",
    "nameEn": "Solukhumbu",
    "nameNe": "सोलुखुम्बु"
  },
  {
    "code": "104",
    "province": "1",
    "nameEn": "Okhaldhunga",
    "nameNe": "ओखलढुंगा"
  },
  {
    "code": "105",
    "province": "1",
    "nameEn": "Khotang",
    "nameNe": "खोटाङ"
  },
  {
    "code": "106",
    "province": "1",
    "nameEn": "Bhojpur",
    "nameNe": "भोजपुर"
  },
  {
    "code": "107",
    "province": "1",
    "nameEn": "Dhankuta",
    "nameNe": "धनकुटा"
  },
  {
    "code": "108",
    "province": "1",
    "nameEn": "Terhathum",
    "nameNe": "तेह्रथुम"
  },
  {
    "code": "109",
    "province": "1",
    "nameEn": "Panchthar",
    "nameNe": "पाँचथर"
  },
  {
    "code": "110",
    "province": "1",
    "nameEn": "Ilam",
    "nameNe": "इलाम"
  },
  {
    "code": "111",
    "province": "1",
    "nameEn": "Jhapa",
    "nameNe": "झापा"
  },
  {
    "code": "112",
    "province": "1",
    "nameEn": "Morang",
    "nameNe": "मोरङ"
  },
  {
    "code": "113",
    "province": "1",
    "nameEn": "Sunsari",
    "nameNe": "सुनसरी"
  },
  {
    "code": "114",
    "province": "1",
    "nameEn": "Udayapur",
    "nameNe": "उदयपुर"
  },
  {
    "code": "201",
    "province": "2",
    "nameEn": "Saptari",
    "nameNe": "सप्तरी"
  },
  {
    "code": "202",
    "province": "2",
    "nameEn": "Siraha",
    "nameNe": "सिराहा"
  },
  {
    "code": "203",
    "province": "2",
    "nameEn": "Dhanusa",
    "nameNe": "धनुषा"
  },
  {
    "code": "204",
    "province": "2",
    "nameEn": "Mahottari",
    "nameNe": "महोत्तरी"
  },
  {
    "code": "205",
    "province": "2",
    "nameEn": "Sarlahi",
    "nameNe": "सर्लाही"
  },
  {
    "code": "206",
    "province": "2",
    "nameEn": "Rautahat",
    "nameNe": "रौतहट"
  },
  {
    "code": "207",
    "province": "2",
    "nameEn": "Bara",
    "nameNe": "बारा"
  },
  {
    "code": "208",
    "province": "2",
    "nameEn": "Parsa",
    "nameNe": "पर्सा"
  },
  {
    "code": "301",
    "province": "3",
    "nameEn": "Dolakha",
    "nameNe": "दोलखा"
  },
  {
    "code": "302",
    "province": "3",
    "nameEn": "Sindhupalchok",
    "nameNe": "सिन्धुपाल्चोक"
  },
  {
    "code": "303",
    "province": "3",
    "nameEn": "Rasuwa",
    "nameNe": "रसुवा"
  },
  {
    "code": "304",
    "province": "3",
    "nameEn": "Dhading",
    "nameNe": "धादिङ"
  },
  {
    "code": "305",
    "province": "3",
    "nameEn": "Nuwakot",
    "nameNe": "नुवाकोट"
  },
  {
    "code": "306",
    "province": "3",
    "nameEn": "Kathmandu",
    "nameNe": "काठमाण्डौं"
  },
  {
    "code": "307",
    "province": "3",
    "nameEn": "Bhaktapur",
    "nameNe": "भक्तपुर"
  },
  {
    "code": "308",
    "province": "3",
    "nameEn": "Lalitpur",
    "nameNe": "ललितपुर"
  },
  {
    "code": "309",
    "province": "3",
    "nameEn": "Kavrepalanchok",
    "nameNe": "काभ्रेपलाञ्चोक"
  },
  {
    "code": "310",
    "province": "3",
    "nameEn": "Ramechhap",
    "nameNe": "रामेछाप"
  },
  {
    "code": "311",
    "province": "3",
    "nameEn": "Sindhuli",
    "nameNe": "सिन्धुली"
  },
  {
    "code": "312",
    "province": "3",
    "nameEn": "Makwanpur",
    "nameNe": "मकवानपुर"
  },
  {
    "code": "313",
    "province": "3",
    "nameEn": "Chitawan",
    "nameNe": "चितवन"
  },
  {
    "code": "401",
    "province": "4",
    "nameEn": "Gorkha",
    "nameNe": "गोरखा"
  },
  {
    "code": "402",
    "province": "4",
    "nameEn": "Manang",
    "nameNe": "मनाङ"
  },
  {
    "code": "403",
    "province": "4",
    "nameEn": "Mustang",
    "nameNe": "मुस्ताङ"
  },
  {
    "code": "404",
    "province": "4",
    "nameEn": "Myagdi",
    "nameNe": "म्याग्दी"
  },
  {
    "code": "405",
    "province": "4",
    "nameEn": "Kaski",
    "nameNe": "कास्की"
  },
  {
    "code": "406",
    "province": "4",
    "nameEn": "Lamjung",
    "nameNe": "लमजुङ"
  },
  {
    "code": "407",
    "province": "4",
    "nameEn": "Tanahu",
    "nameNe": "तनहुँ"
  },
  {
    "code": "408",
    "province": "4",
    "nameEn": "Nawalparasi East",
    "nameNe": "नवलपरासी (बर्दघाट सुस्ता पूर्व)"
  },
  {
    "code": "409",
    "province": "4",
    "nameEn": "Syangja",
    "nameNe": "स्याङजा"
  },
  {
    "code": "410",
    "province": "4",
    "nameEn": "Parbat",
    "nameNe": "पर्वत"
  },
  {
    "code": "411",
    "province": "4",
    "nameEn": "Baglung",
    "nameNe": "बाग्लुङ"
  },
  {
    "code": "501",
    "province": "5",
    "nameEn": "Rukum East",
    "nameNe": "रुकुम (पूर्वी भाग)"
  },
  {
    "code": "502",
    "province": "5",
    "nameEn": "Rolpa",
    "nameNe": "रोल्पा"
  },
  {
    "code": "503",
    "province": "5",
    "nameEn": "Pyuthan",
    "nameNe": "प्यूठान"
  },
  {
    "code": "504",
    "province": "5",
    "nameEn": "Gulmi",
    "nameNe": "गुल्मी"
  },
  {
    "code": "505",
    "province": "5",
    "nameEn": "Arghakhanchi",
    "nameNe": "अर्घाखाँची"
  },
  {
    "code": "506",
    "province": "5",
    "nameEn": "Palpa",
    "nameNe": "पाल्पा"
  },
  {
    "code": "507",
    "province": "5",
    "nameEn": "Nawalparasi West",
    "nameNe": "नवलपरासी (बर्दघाट सुस्ता पश्चिम)"
  },
  {
    "code": "508",
    "province": "5",
    "nameEn": "Rupandehi",
    "nameNe": "रूपन्देही"
  },
  {
    "code": "509",
    "province": "5",
    "nameEn": "Kapilbastu",
    "nameNe": "कपिलबस्तु"
  },
  {
    "code": "510",
    "province": "5",
    "nameEn": "Dang",
    "nameNe": "दाङ"
  },
  {
    "code": "511",
    "province": "5",
    "nameEn": "Banke",
    "nameNe": "बाँके"
  },
  {
    "code": "512",
    "province": "5",
    "nameEn": "Bardiya",
    "nameNe": "बर्दिया"
  },
  {
    "code": "601",
    "province": "6",
    "nameEn": "Dolpa",
    "nameNe": "डोल्पा"
  },
  {
    "code": "602",
    "province": "6",
    "nameEn": "Mugu",
    "nameNe": "मुगु"
  },
  {
    "code": "603",
    "province": "6",
    "nameEn": "Humla",
    "nameNe": "हुम्ला"
  },
  {
    "code": "604",
    "province": "6",
    "nameEn": "Jumla",
    "nameNe": "जुम्ला"
  },
  {
    "code": "605",
    "province": "6",
    "nameEn": "Kalikot",
    "nameNe": "कालिकोट"
  },
  {
    "code": "606",
    "province": "6",
    "nameEn": "Dailekh",
    "nameNe": "दैलेख"
  },
  {
    "code": "607",
    "province": "6",
    "nameEn": "Jajarkot",
    "nameNe": "जाजरकोट"
  },
  {
    "code": "608",
    "province": "6",
    "nameEn": "Rukum West",
    "nameNe": "रुकुम (पश्चिम भाग)"
  },
  {
    "code": "609",
    "province": "6",
    "nameEn": "Salyan",
    "nameNe": "सल्यान"
  },
  {
    "code": "610",
    "province": "6",
    "nameEn": "Surkhet",
    "nameNe": "सुर्खेत"
  },
  {
    "code": "701",
    "province": "7",
    "nameEn": "Bajura",
    "nameNe": "बाजुरा"
  },
  {
    "code": "702",
    "province": "7",
    "nameEn": "Bajhang",
    "nameNe": "बझाङ"
  },
  {
    "code": "703",
    "province": "7",
    "nameEn": "Darchula",
    "nameNe": "दार्चुला"
  },
  {
    "code": "704",
    "province": "7",
    "nameEn": "Baitadi",
    "nameNe": "बैतडी"
  },
  {
    "code": "705",
    "province": "7",
    "nameEn": "Dadeldhura",
    "nameNe": "डडेल्धुरा"
  },
  {
    "code": "706",
    "province": "7",
    "nameEn": "Doti",
    "nameNe": "डोटी"
  },
  {
    "code": "707",
    "province": "7",
    "nameEn": "Achham",
    "nameNe": "अछाम"
  },
  {
    "code": "708",
    "province": "7",
    "nameEn": "Kailali",
    "nameNe": "कैलाली"
  },
  {
    "code": "709",
    "province": "7",
    "nameEn": "Kanchanpur",
    "nameNe": "कञ्चनपुर"
  }
] as const;
