// Generated by `pnpm generate:admin` from src/admin/data/raw/*.json.
// DO NOT EDIT. Revision: gov-2026-09. See PROVENANCE.md.
import type { Province } from '../types.js';

export const PROVINCES: readonly Province[] = [
  {
    "code": "1",
    "nameEn": "Koshi Province",
    "nameNe": "कोशी प्रदेश"
  },
  {
    "code": "2",
    "nameEn": "Madhesh Province",
    "nameNe": "मधेश प्रदेश"
  },
  {
    "code": "3",
    "nameEn": "Bagmati Province",
    "nameNe": "बागमती प्रदेश"
  },
  {
    "code": "4",
    "nameEn": "Gandaki Province",
    "nameNe": "गण्डकी प्रदेश"
  },
  {
    "code": "5",
    "nameEn": "Lumbini Province",
    "nameNe": "लुम्बिनी प्रदेश"
  },
  {
    "code": "6",
    "nameEn": "Karnali Province",
    "nameNe": "कर्णाली प्रदेश"
  },
  {
    "code": "7",
    "nameEn": "Sudurpashchim Province",
    "nameNe": "सुदूरपश्चिम प्रदेश"
  }
] as const;
