/* This file is generated by scripts/generate-data.mjs. */
export interface MetadataDate {
  readonly year: number;
  readonly month: number;
  readonly day: number;
}

export interface ReferencePair {
  readonly bs: MetadataDate;
  readonly ad: MetadataDate;
  readonly note: string;
}

export interface DateMetadata {
  readonly bsStart: MetadataDate;
  readonly bsEnd: MetadataDate;
  readonly adStart: MetadataDate;
  readonly adEnd: MetadataDate;
  readonly totalDays: number;
  readonly checksum: string;
  readonly sourceRevision: string;
  readonly referencePair: ReferencePair;
}

const bsStart = Object.freeze({ year: 2000, month: 1, day: 1 });
const bsEnd = Object.freeze({ year: 2090, month: 12, day: 30 });
const adStart = Object.freeze({ year: 1943, month: 4, day: 14 });
const adEnd = Object.freeze({ year: 2034, month: 4, day: 13 });
const referencePair = Object.freeze({
  bs: Object.freeze({ year: 2000, month: 1, day: 1 }),
  ad: Object.freeze({ year: 1943, month: 4, day: 14 }),
  note: 'anchor for wip - to be verified in Ticket 05',
});

export const metadata: DateMetadata = Object.freeze({
  bsStart,
  bsEnd,
  adStart,
  adEnd,
  totalDays: 33238,
  checksum: 'd776359d975d4ace',
  sourceRevision: 'working-2026-08-22',
  referencePair,
});
